"""
data_generator.py - Synthetic email queue generator.
Includes standard emails + adversarial emails designed to trick agents.
"""
import random
from typing import List

# ── Standard emails ───────────────────────────────────────────────────────────
STANDARD_EMAILS = [
    # BILLING (8)
    {
        "subject": "Charged twice this month - urgent",
        "body": "I noticed two identical charges of $99 on my statement this month. This is causing my account to go negative. Please refund one charge immediately. My account number is #44821.",
        "sender": "Sarah Mitchell <s.mitchell@gmail.com>",
        "timestamp": "2024-11-04T09:15:00Z",
        "ground_truth_priority": "critical",
        "ground_truth_category": "billing",
        "ground_truth_action": "escalate",
        "adversarial": False,
    },
    {
        "subject": "Cancel my subscription",
        "body": "I would like to cancel my subscription effective end of this billing cycle. I've enjoyed the service but no longer need it. Please confirm cancellation and ensure I'm not charged next month.",
        "sender": "James Okafor <james.okafor@outlook.com>",
        "timestamp": "2024-11-05T14:22:00Z",
        "ground_truth_priority": "medium",
        "ground_truth_category": "billing",
        "ground_truth_action": "respond",
        "adversarial": False,
    },
    {
        "subject": "Need invoice for tax purposes",
        "body": "Could you please send me invoices for all purchases made this year? I need them for my annual tax filing. My account email is registered under this address. Thank you.",
        "sender": "Linda Zhao <linda.zhao@company.com>",
        "timestamp": "2024-11-06T11:05:00Z",
        "ground_truth_priority": "low",
        "ground_truth_category": "billing",
        "ground_truth_action": "respond",
        "adversarial": False,
    },
    {
        "subject": "Payment method declined",
        "body": "My payment was declined when trying to upgrade my plan. I've verified my card details are correct. This is preventing me from accessing premium features I need for work today.",
        "sender": "Carlos Rivera <c.rivera@startup.io>",
        "timestamp": "2024-11-07T08:45:00Z",
        "ground_truth_priority": "high",
        "ground_truth_category": "billing",
        "ground_truth_action": "respond",
        "adversarial": False,
    },
    {
        "subject": "Requesting refund for unused month",
        "body": "I cancelled my account three weeks ago but was still charged for a full month. I'd like a prorated refund for the unused portion. I have the cancellation confirmation email as reference.",
        "sender": "Priya Nair <priya.nair@freelance.net>",
        "timestamp": "2024-11-08T16:30:00Z",
        "ground_truth_priority": "high",
        "ground_truth_category": "billing",
        "ground_truth_action": "respond",
        "adversarial": False,
    },
    {
        "subject": "Upgrade plan pricing question",
        "body": "I'm considering upgrading from the starter to the professional plan. Can you confirm what the monthly cost will be and whether my current data and settings will be preserved during the upgrade?",
        "sender": "Omar Hassan <o.hassan@consulting.com>",
        "timestamp": "2024-11-09T10:00:00Z",
        "ground_truth_priority": "low",
        "ground_truth_category": "billing",
        "ground_truth_action": "respond",
        "adversarial": False,
    },
    {
        "subject": "Annual billing discount not applied",
        "body": "I switched to annual billing last week to get the 20% discount but my invoice still shows the monthly rate. Please correct this and issue a credit for the difference.",
        "sender": "Nina Petrov <n.petrov@agency.eu>",
        "timestamp": "2024-11-10T13:20:00Z",
        "ground_truth_priority": "high",
        "ground_truth_category": "billing",
        "ground_truth_action": "respond",
        "adversarial": False,
    },
    {
        "subject": "Unauthorized charge on my account",
        "body": "There is a $299 charge on my account that I did not authorize. I have never signed up for the enterprise plan. I need this reversed immediately and my account secured. This may be fraud.",
        "sender": "Derek Walsh <d.walsh@personal.ie>",
        "timestamp": "2024-11-11T07:30:00Z",
        "ground_truth_priority": "critical",
        "ground_truth_category": "billing",
        "ground_truth_action": "escalate",
        "adversarial": False,
    },
    # TECHNICAL (8)
    {
        "subject": "URGENT: Entire team locked out - board meeting in 1 hour",
        "body": "Our entire 50-person team cannot log into the platform as of 8am this morning. We have a critical board presentation in 1 hour that requires access to your dashboards. This is a complete business emergency. Please escalate immediately.",
        "sender": "David Chen <d.chen@enterprise.com>",
        "timestamp": "2024-11-04T08:02:00Z",
        "ground_truth_priority": "critical",
        "ground_truth_category": "technical",
        "ground_truth_action": "escalate",
        "adversarial": False,
    },
    {
        "subject": "Dashboard crashes every time on load",
        "body": "The main dashboard crashes immediately after logging in on Chrome v120. I've cleared cache and tried incognito mode with no success. This started happening after yesterday's update.",
        "sender": "Emma Thompson <emma.t@designstudio.co>",
        "timestamp": "2024-11-05T10:18:00Z",
        "ground_truth_priority": "high",
        "ground_truth_category": "technical",
        "ground_truth_action": "respond",
        "adversarial": False,
    },
    {
        "subject": "Export to CSV not working",
        "body": "The CSV export button on the reports page doesn't do anything when clicked. No error message appears. I need to export my monthly data for a client presentation. Other export formats work fine.",
        "sender": "Marcus Johnson <m.johnson@analytics.biz>",
        "timestamp": "2024-11-06T13:40:00Z",
        "ground_truth_priority": "medium",
        "ground_truth_category": "technical",
        "ground_truth_action": "respond",
        "adversarial": False,
    },
    {
        "subject": "Slack integration stopped sending notifications",
        "body": "Our Slack integration stopped working about 2 days ago. We no longer receive any notifications in our #alerts channel. I've tried reconnecting the integration but the issue persists.",
        "sender": "Aisha Patel <aisha.patel@techcorp.dev>",
        "timestamp": "2024-11-07T15:55:00Z",
        "ground_truth_priority": "medium",
        "ground_truth_category": "technical",
        "ground_truth_action": "respond",
        "adversarial": False,
    },
    {
        "subject": "App feels slow lately",
        "body": "Over the past week the app has felt noticeably slower than usual, especially when loading reports. Load times seem to be around 10-15 seconds which is much longer than before. Not urgent but wanted to flag it.",
        "sender": "Tom Nguyen <t.nguyen@smallbiz.com>",
        "timestamp": "2024-11-08T09:20:00Z",
        "ground_truth_priority": "low",
        "ground_truth_category": "technical",
        "ground_truth_action": "respond",
        "adversarial": False,
    },
    {
        "subject": "API rate limit errors in production",
        "body": "We are hitting 429 rate limit errors on your API in our production environment. This is causing failures in our customer-facing product. We need either a rate limit increase or guidance on batching requests.",
        "sender": "Raj Mehta <raj.mehta@saasproduct.io>",
        "timestamp": "2024-11-09T11:45:00Z",
        "ground_truth_priority": "high",
        "ground_truth_category": "technical",
        "ground_truth_action": "escalate",
        "adversarial": False,
    },
    {
        "subject": "Two-factor authentication not sending SMS",
        "body": "I enabled 2FA on my account but I'm not receiving the SMS verification codes. I've confirmed my phone number is correct. I'm completely locked out of my account.",
        "sender": "Fatima Al-Rashid <f.alrashid@media.ae>",
        "timestamp": "2024-11-10T16:10:00Z",
        "ground_truth_priority": "high",
        "ground_truth_category": "technical",
        "ground_truth_action": "respond",
        "adversarial": False,
    },
    {
        "subject": "Webhook endpoint not receiving events",
        "body": "Our webhook endpoint stopped receiving events from your platform 6 hours ago. We've verified our endpoint is live and accepting connections. No events are being delivered at all.",
        "sender": "Lucas Ferreira <l.ferreira@devteam.br>",
        "timestamp": "2024-11-11T14:00:00Z",
        "ground_truth_priority": "high",
        "ground_truth_category": "technical",
        "ground_truth_action": "respond",
        "adversarial": False,
    },
    # GENERAL (8)
    {
        "subject": "Just wanted to say thank you",
        "body": "I've been using your product for 6 months now and it has genuinely transformed how my team works. The recent updates to the dashboard were exactly what we needed. Keep up the amazing work!",
        "sender": "Rachel Kim <rachel.kim@happycustomer.com>",
        "timestamp": "2024-11-04T17:00:00Z",
        "ground_truth_priority": "low",
        "ground_truth_category": "general",
        "ground_truth_action": "archive",
        "adversarial": False,
    },
    {
        "subject": "Feature suggestion: dark mode",
        "body": "Would love to see a dark mode option added to the interface. I work late hours and the bright white background is hard on my eyes. Many modern apps offer this and I think your users would appreciate it.",
        "sender": "Ben Kowalski <ben.k@nightowl.dev>",
        "timestamp": "2024-11-05T22:10:00Z",
        "ground_truth_priority": "low",
        "ground_truth_category": "general",
        "ground_truth_action": "respond",
        "adversarial": False,
    },
    {
        "subject": "How do I add team members?",
        "body": "I just signed up for the team plan and I'm trying to invite my colleagues but can't find where to do this. I've looked through the settings but the option isn't obvious. Can you point me in the right direction?",
        "sender": "Sofia Andersen <sofia.a@newstartup.io>",
        "timestamp": "2024-11-06T10:30:00Z",
        "ground_truth_priority": "medium",
        "ground_truth_category": "general",
        "ground_truth_action": "respond",
        "adversarial": False,
    },
    {
        "subject": "Partnership opportunity",
        "body": "I represent a marketing agency with 200+ clients that could benefit from your platform. I'd love to discuss a potential partnership or reseller arrangement. Who would be the right person to speak with about this?",
        "sender": "Victor Osei <v.osei@marketingpro.agency>",
        "timestamp": "2024-11-07T11:45:00Z",
        "ground_truth_priority": "low",
        "ground_truth_category": "general",
        "ground_truth_action": "respond",
        "adversarial": False,
    },
    {
        "subject": "Can't find my old account",
        "body": "I had an account with you about 2 years ago under a different email address. I'd like to reactivate it if possible. I don't remember the exact email used. Is there a way to look up accounts by name or payment method?",
        "sender": "Hannah Brooks <h.brooks@personal.me>",
        "timestamp": "2024-11-08T14:15:00Z",
        "ground_truth_priority": "medium",
        "ground_truth_category": "general",
        "ground_truth_action": "respond",
        "adversarial": False,
    },
    {
        "subject": "Onboarding webinar recording available?",
        "body": "I missed the onboarding webinar last Tuesday. Is there a recording I can watch? I'm new to the platform and want to make sure I'm using all the features correctly.",
        "sender": "Yuki Tanaka <y.tanaka@corp.jp>",
        "timestamp": "2024-11-09T09:00:00Z",
        "ground_truth_priority": "low",
        "ground_truth_category": "general",
        "ground_truth_action": "respond",
        "adversarial": False,
    },
    {
        "subject": "Accessibility question about screen reader support",
        "body": "I use a screen reader due to a visual impairment. I'm evaluating your platform for my team. Can you confirm whether your interface is compatible with NVDA and JAWS screen readers?",
        "sender": "Michael Torres <m.torres@nonprofit.org>",
        "timestamp": "2024-11-10T15:30:00Z",
        "ground_truth_priority": "medium",
        "ground_truth_category": "general",
        "ground_truth_action": "respond",
        "adversarial": False,
    },
    {
        "subject": "Data export before account deletion",
        "body": "I've decided to close my account. Before I do, I want to export all my data including reports, settings, and history. Can you guide me through the data export process?",
        "sender": "Claire Dubois <c.dubois@personal.fr>",
        "timestamp": "2024-11-11T12:00:00Z",
        "ground_truth_priority": "medium",
        "ground_truth_category": "general",
        "ground_truth_action": "respond",
        "adversarial": False,
    },
    # SPAM (8)
    {
        "subject": "Congratulations! You've won $5,000",
        "body": "You have been selected as our lucky winner! Claim your $5,000 prize by clicking the link below and entering your bank details. This offer expires in 24 hours. Act now!",
        "sender": "Prize Center <noreply@prize-winner-2024.xyz>",
        "timestamp": "2024-11-04T03:12:00Z",
        "ground_truth_priority": "low",
        "ground_truth_category": "spam",
        "ground_truth_action": "delete",
        "adversarial": False,
    },
    {
        "subject": "URGENT: 10x your investment tonight",
        "body": "Our AI trading bot made 847% returns last month. Join thousands of investors who quit their jobs. Limited spots available. Send 0.1 BTC to get started. 100% guaranteed returns.",
        "sender": "Crypto Profits <admin@cryptobot-gains.ru>",
        "timestamp": "2024-11-05T01:30:00Z",
        "ground_truth_priority": "low",
        "ground_truth_category": "spam",
        "ground_truth_action": "delete",
        "adversarial": False,
    },
    {
        "subject": "Your account has been compromised - verify now",
        "body": "We detected suspicious activity on your account. Click here immediately to verify your identity and secure your account. Failure to verify within 2 hours will result in account suspension.",
        "sender": "Security Team <security@account-verify-alert.com>",
        "timestamp": "2024-11-07T04:45:00Z",
        "ground_truth_priority": "low",
        "ground_truth_category": "spam",
        "ground_truth_action": "delete",
        "adversarial": False,
    },
    {
        "subject": "Boost your website to #1 on Google guaranteed",
        "body": "Our SEO experts can get your website to the first page of Google in just 30 days, guaranteed! We've helped 10,000+ businesses. Reply for a free audit. Special discount ends Friday.",
        "sender": "SEO Masters <outreach@seo-guaranteed-results.biz>",
        "timestamp": "2024-11-08T07:20:00Z",
        "ground_truth_priority": "low",
        "ground_truth_category": "spam",
        "ground_truth_action": "delete",
        "adversarial": False,
    },
    {
        "subject": "Free trial extended just for you",
        "body": "As a valued member we are extending your free trial by 30 days at no cost. Simply click the link and re-enter your payment details to activate. No charge until you decide to upgrade.",
        "sender": "Membership Team <offers@free-trial-extend.net>",
        "timestamp": "2024-11-09T02:00:00Z",
        "ground_truth_priority": "low",
        "ground_truth_category": "spam",
        "ground_truth_action": "delete",
        "adversarial": False,
    },
    {
        "subject": "You have a pending package delivery",
        "body": "Your package could not be delivered. Pay a $2.99 redelivery fee to reschedule. Click the link to pay now or your package will be returned to sender.",
        "sender": "Delivery Notice <noreply@parcel-redeliver.xyz>",
        "timestamp": "2024-11-10T05:15:00Z",
        "ground_truth_priority": "low",
        "ground_truth_category": "spam",
        "ground_truth_action": "delete",
        "adversarial": False,
    },
    {
        "subject": "Exclusive business loan offer - no credit check",
        "body": "Get up to $500,000 in business funding within 24 hours. No credit check required. No collateral. 100% approval rate. Reply with your business name and annual revenue to get started.",
        "sender": "Business Capital <loans@instant-biz-funding.co>",
        "timestamp": "2024-11-11T06:45:00Z",
        "ground_truth_priority": "low",
        "ground_truth_category": "spam",
        "ground_truth_action": "delete",
        "adversarial": False,
    },
    {
        "subject": "Your Microsoft account will be suspended",
        "body": "Unusual sign-in activity detected on your Microsoft account. Your account will be suspended in 24 hours unless you verify your identity. Click here to verify and keep your account active.",
        "sender": "Microsoft Support <support@microsoft-account-alert.org>",
        "timestamp": "2024-11-12T03:30:00Z",
        "ground_truth_priority": "low",
        "ground_truth_category": "spam",
        "ground_truth_action": "delete",
        "adversarial": False,
    },
]

# ── Adversarial emails (disguised spam / misleading context) ──────────────────
ADVERSARIAL_EMAILS = [
    # Spam disguised as billing
    {
        "subject": "Your invoice #INV-99821 is overdue",
        "body": "Please pay your overdue invoice immediately to avoid service interruption. Click the payment link below. This is your final notice before we send to collections.",
        "sender": "Billing Dept <billing@fake-invoices.net>",
        "timestamp": "2024-11-06T06:00:00Z",
        "ground_truth_priority": "low",
        "ground_truth_category": "spam",
        "ground_truth_action": "delete",
        "adversarial": True,
        "adversarial_type": "spam_as_billing",
    },
    {
        "subject": "Refund processed - confirm your bank details",
        "body": "We have processed a refund of $149 to your account. To complete the transfer please confirm your bank account number and routing number by clicking the secure link below.",
        "sender": "Refunds Team <refunds@payment-confirm-secure.com>",
        "timestamp": "2024-11-08T10:00:00Z",
        "ground_truth_priority": "low",
        "ground_truth_category": "spam",
        "ground_truth_action": "delete",
        "adversarial": True,
        "adversarial_type": "spam_as_billing",
    },
    {
        "subject": "Subscription renewal failed - update payment now",
        "body": "Your subscription renewal failed due to an expired card. Update your payment method within 24 hours to avoid losing access. Click here to update your billing information securely.",
        "sender": "Account Services <noreply@subscription-renewal-alert.net>",
        "timestamp": "2024-11-09T08:30:00Z",
        "ground_truth_priority": "low",
        "ground_truth_category": "spam",
        "ground_truth_action": "delete",
        "adversarial": True,
        "adversarial_type": "spam_as_billing",
    },
    # Spam disguised as technical/security
    {
        "subject": "Critical security vulnerability in your account",
        "body": "Our security team detected a critical vulnerability affecting your account. You must install our security patch immediately by downloading the attached file. Failure to act within 12 hours may result in data loss.",
        "sender": "Security Response <security@critical-patch-alert.io>",
        "timestamp": "2024-11-07T02:00:00Z",
        "ground_truth_priority": "low",
        "ground_truth_category": "spam",
        "ground_truth_action": "delete",
        "adversarial": True,
        "adversarial_type": "spam_as_technical",
    },
    {
        "subject": "Your API key has been exposed",
        "body": "We detected your API key in a public GitHub repository. Click the link below to immediately rotate your key and secure your account before unauthorized access occurs.",
        "sender": "DevOps Alert <alerts@api-security-monitor.net>",
        "timestamp": "2024-11-10T04:00:00Z",
        "ground_truth_priority": "low",
        "ground_truth_category": "spam",
        "ground_truth_action": "delete",
        "adversarial": True,
        "adversarial_type": "spam_as_technical",
    },
    # Legitimate urgent email that looks like spam
    {
        "subject": "FINAL WARNING: Account deletion in 24 hours",
        "body": "This is a final warning that your account is scheduled for deletion due to 12 months of inactivity. If you wish to keep your account and all associated data, please log in within 24 hours. No action required if you wish to proceed with deletion.",
        "sender": "Account Management <accounts@ourplatform.com>",
        "timestamp": "2024-11-11T09:00:00Z",
        "ground_truth_priority": "high",
        "ground_truth_category": "general",
        "ground_truth_action": "respond",
        "adversarial": True,
        "adversarial_type": "legitimate_looks_like_spam",
    },
    # Legitimate billing that looks like spam
    {
        "subject": "You have been charged $0.00",
        "body": "This is a confirmation that your free trial has started. You will not be charged until your trial ends on December 1st. Your plan: Professional. No credit card required during trial.",
        "sender": "Billing <billing@ourplatform.com>",
        "timestamp": "2024-11-12T10:00:00Z",
        "ground_truth_priority": "low",
        "ground_truth_category": "billing",
        "ground_truth_action": "archive",
        "adversarial": True,
        "adversarial_type": "legitimate_looks_like_spam",
    },
    # Technical issue with misleading urgency
    {
        "subject": "CRITICAL: Data breach detected on your account",
        "body": "I think my account may have been accessed by someone else. I noticed login activity from an IP address in a country I've never visited. Can you check my account access logs and help me secure it?",
        "sender": "Alex Morgan <a.morgan@user.com>",
        "timestamp": "2024-11-13T11:00:00Z",
        "ground_truth_priority": "critical",
        "ground_truth_category": "technical",
        "ground_truth_action": "escalate",
        "adversarial": True,
        "adversarial_type": "legitimate_urgent",
    },
]

ALL_EMAILS = STANDARD_EMAILS + ADVERSARIAL_EMAILS


def generate_email_queue(n: int = 10, seed: int = 42, adversarial: bool = False) -> List[dict]:
    """
    Generate a queue of n emails.
    adversarial=True includes adversarial emails in the pool.
    Uses seeded randomness for reproducibility.
    """
    rng = random.Random(seed)
    pool = ALL_EMAILS if adversarial else STANDARD_EMAILS

    if n <= len(pool):
        selected = rng.sample(pool, n)
    else:
        selected = rng.choices(pool, k=n)

    emails = []
    for i, template in enumerate(selected):
        email = dict(template)
        email["id"] = f"email_{i + 1:03d}"
        emails.append(email)

    return emails
